### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-sandbox/wizard-tester#24]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Documentation

- [ ] No TODO markers left in README.md
- Found 4 fragment(s) in the README.md or the output while expecting exactly 0 
- [x] We need better headings

- [x] Have at least 3 TODOs

## git

- [x] Make at least one commit, you moron

- [ ] Make at least 1000 commits, you moron
- Found 110 commit(s) in the Git repository 
- [ ] Make at least 9987000 commits, you moron
- Found 110 commit(s) in the Git repository 

## Percent complete

Based on the checks achieved, this assignment is `%` complete.
